<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findRelatedProductByCategoryId($categoryId)
    {
        $count = $this->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->getQuery()
            ->getSingleScalarResult();

        return $this->createQueryBuilder('u')
            ->where('u.category = :category')
            ->setFirstResult(rand(0, $count - 1))
            ->setMaxResults(1)
            ->setParameter('category', $categoryId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
